name: Lint with flake8

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install/upgrade pip
      run: |
        python -m pip install --upgrade pip
        pip install flake8
    - name: Lint with flake8
      run: flake8 socha
