name: Release

on:
  push:
    tags:
    - 'v*'

jobs:
  release:
    name: Build and release
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2.0.0
    - name: Setup Python 3.8
      uses: actions/setup-python@v1.1.1
      with:
        python-version: 3.8
    - name: Install C++ extension
      run: python setup.py install
    - name: Build
      run: make build
    - name: Release
      id: release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
    - name: Add build to release
      uses: actions/upload-release-asset@v1.0.2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.release.outputs.upload_url }}
        asset_path: ./socha.zip
        asset_name: socha.zip
        asset_content_type: application/zip
